bar:
  height: 26
  location: top
  background: 000000ff


  left:
    - dwl:
      number-of-tags: 9
      dwl-info-filename: "/home/ogromny/dwl_info"
      name-of-tags: [ , , , , , , , ,  ]
      content:
        list:
          items:
            - map:
              conditions:
                # default tag
                id == 0: {string: {text: "{layout} {title}"}}

                selected: {string: {text: "-> {name}"}}
                ~empty: {string: {text: "{name}"}}
                urgent: {string: {text: "=> {name} <="}}

  right:
    - clock:
        content:
          - string: {text: , font: "Font Awesome 6 Free:style=solid:size=12"}
          - string: {text: "{date}", right-margin: 5}
          - string: {text: , font: "Font Awesome 6 Free:style=solid:size=12"}
          - string: {text: "{time}"}
