# mangobar
exec_once=mangobar &
# fcitx5
exec_once=fcitx5 --replace -d >/dev/null 2>&1 &
# obs-studio
exec_once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=wlroots
# Keep clipboard content after app closes
exec_once=wl-clip-persist --clipboard regular --reconnect-tries 0 &
# Watch clipboard and store history
exec_once=wl-paste --type text --watch cliphist store &
# notification
exec_once=mako -c ~/.config/mako/config
# wallpaper
exec_once=swaybg --image ~/.config/mango/wallpaper.png --mode fill
